### ISSUE TITLE
 Why is fucking atsl sending my discord ls file?

### ISSUE THREAD

**Issue by aws2680** [BerkanYildiz/Diskord.NET#1]
Why is fucking atsl sending my discord ls file?

**Comment by BerkanYildiz** [comment]
We are not sending anything.
We are using a DiscordClient to update the account game status.
You’ll see a « Playing ATsl v1.0.3a » when using it.

**Comment by BerkanYildiz** [comment]
If you continue messing with our files thought, that wil have repercussions.
